# Generated by Django 2.2.7 on 2019-11-06 02:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset1', models.TextField(default=None, validators=[core.models.validate_dataset])),
                ('mean1', models.FloatField(default=None, null=True)),
                ('sd1', models.FloatField(default=None, null=True)),
                ('n1', models.IntegerField(default=None, null=True)),
                ('dataset2', models.TextField(default=None, validators=[core.models.validate_dataset])),
                ('mean2', models.FloatField(default=None, null=True)),
                ('sd2', models.FloatField(default=None, null=True)),
                ('n2', models.IntegerField(default=None, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
